# Generated by Django 6.1 on 2026-08-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myExpense', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', '🍔 Food'), ('transport', '🚕 Transport'), ('housing', '🏠 Housing'), ('utilities', '💡 Utilities'), ('shopping', '🛒 Shopping'), ('health', '💊 Health'), ('education', '🎓 Education'), ('entertainment', '🎉 Entertainment'), ('other', '📦 Other')], default='other', max_length=20),
        ),
    ]
